name: main.linux.temurin.lts

on:
  push:
    branches: [ develop, feature/*, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build
        run: mvn --errors -Dbnd.baseline.skip=true -Denforcer.skip=true clean verify
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: com.io7m.primogenitor.tests/target/site/jacoco-aggregate/jacoco.xml
